package assets.virologist.behavior.infectbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.infectbehavior.InfectBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.agent.Agent;
import assets.virologist.Virologist;

/** The field.virologist.behavior which decides if the field.virologist.Virologist can infect another field.virologist.Virologist */
public interface InfectBehavior {
	/**
	 *
	 * @param v1 the field.virologist.Virologist who wants to infect
	 * @param v2 the target of the action
	 * @param a the Agents v1 wants to infect v2 with
	 */
	void InfectVirologist(Virologist v1, Virologist v2, Agent a);

	void InfectRandomOff(Virologist v1, Virologist v2, Agent a);
}
