package assets.virologist.behavior.infectbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.infectbehavior.NotInfect.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.agent.Agent;
import assets.virologist.Virologist;
public class NotInfect implements InfectBehavior, java.io.Serializable {
    /**
     * Nothing happens.
     *
     * @param v1 the field.virologist.Virologist who wants to infect
     * @param v2 the target of the action
     * @param a the Agents v1 wants to infect v2 with
     */
    @Override
    public void InfectVirologist(Virologist v1, Virologist v2, Agent a) {
    }

    @Override
    public void InfectRandomOff(Virologist v1, Virologist v2, Agent a) {

    }
}
