package assets.virologist;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.Route.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import java.util.ArrayList;

import assets.field.Field;

/** The Fields the field.virologist.Virologist was on*/
public class Route implements java.io.Serializable{
	/** Constructor*/
	Route(){
		fields = new ArrayList<>();
	}
	/** The List where the field.virologist.Route Stores the Fields*/
	public final ArrayList<Field> fields;
	
	/** Returns the Location of the Wizard by looking at the last field.field.Field he moved to*/
	public Field GetLocation() {
		if(fields.isEmpty()){
			return null;
		}
		return fields.get(fields.size()-1);
	}

	public void Add(Field f) {
		fields.add(f);
	}
}
