package collectables.genome;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : collectables.genome.Genome.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.virologist.Virologist;

/**
 * The collectables.genome.Genome is a genetic code to a collectables.agent.Agent. The field.virologist.Virologist can field.virologist.behavior.learnbehavior.Learn a
 * collectables.genome.Genome and field.virologist.behavior.createbehavior.Create the collectables.agent.Agent if he has enough materials
 * */
public abstract class Genome implements java.io.Serializable{
	/**
	 * Creates a collectables.agent.Agent and puts it into the field.Backpack of a field.virologist.Virologist
	 *
	 * @param v the field.virologist.Virologist who creates the collectables.agent.Agent
	 */
	public abstract void CreateAgent(Virologist v);

	/** returns how many collectables.material.Aminoacid is needed to create the collectables.agent.Agent*/
	public abstract int getAminoCost();

	/** returns how many collectables.material.Nucleotide is needed to create the collectables.agent.Agent*/
	public abstract int getNucleoCost();

	public abstract String GetName();
}
