package collectables.genome;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : collectables.genome.GenomeParalysis.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//
import collectables.agent.Paralysis;
import assets.virologist.Virologist;
/** The collectables.genome.GenomeChorea is used to create the collectables.agent.Paralysis collectables.agent.Agent*/
public class GenomeParalysis extends Genome{

	//TODO
	/**
	 * Creates a collectables.agent.Paralysis collectables.agent.Agent and puts it into the field.Backpack of the field.virologist.Virologist that created it
	 *
	 * @param v the field.virologist.Virologist who creates the collectables.agent.Agent
	 */
	public void CreateAgent(Virologist v) {
		Paralysis agent = new Paralysis();
		agent.AddToBackpack(v, v.getBackpack());
	}
	@Override
	public int getAminoCost() {
		return 5;
	}

	@Override
	public int getNucleoCost() {
		return 5;
	}

	@Override
	public String GetName(){return "paralysis";}
}
