package collectables.agent;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : collectables.agent.Chorea.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.virologist.Virologist;
import assets.virologist.behavior.movebehavior.*;

/** collectables.agent.Chorea makes the infected field.virologist.Virologist move to random directions*/
public class Chorea extends Agent{

	/** The number of turns a field.virologist.Virologist can store the collectables.agent.Agent in his field.Backpack.*/
	private static int warranty;

	/** The number of turns a collectables.agent.Agent stays active on an infected field.virologist.Virologist*/
	private static int duration;

	/** Constructor*/
	public Chorea(){
		warranty = baseWarranty;
		duration = effectDuration;
	}

	/** The number of turns the collectables.agent.Agent can be used after its creation*/
	private static final int baseWarranty = 5;
	private static final int effectDuration = 3;

	@Override
	public int getDuration() {
		return duration;
	}

	@Override
	public void setDuration(int duration) {
		Chorea.duration = duration;
	}

	@Override
	public int getWarranty() {
		return warranty;
	}

	@Override
	public void setWarranty(int warranty) {
		Chorea.warranty = warranty;
	}

	/** Applies the effect to the field.virologist.Virologist if there is no stronger effect on him*/
	public void Apply(Virologist v) {
		if(v.GetMoveBehavior().GetPriority() < 1)
			v.SetMoveBehavior(new RandomMove());
	}

	@Override
	public String GetName(){ return "chorea";}
}
