package collectables.agent;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : collectables.agent.Paralysis.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.virologist.behavior.createbehavior.NotCreate;
import assets.virologist.behavior.getstolenbehavior.GetStolen;
import assets.virologist.behavior.infectbehavior.NotInfect;
import assets.virologist.behavior.learnbehavior.NotLearn;
import assets.virologist.behavior.movebehavior.NotMove;
import assets.virologist.behavior.pickupbehavior.NotPickUp;
import assets.virologist.behavior.stealbehavior.NotSteal;
import assets.virologist.*;
import assets.virologist.behavior.dropbehavior.*;

/** The field.virologist.Virologist can not do anything. Other Virologists can steal from him*/
public class Paralysis extends Agent{

	/** The number of turns a field.virologist.Virologist can store the collectables.agent.Agent in his field.Backpack.*/
	private static int warranty;

	/** The number of turns a collectables.agent.Agent stays active on an infected field.virologist.Virologist*/
	private static int duration;

	/** Constructor*/
	public Paralysis(){
		warranty = baseWarranty;
		duration = effectDuration;
	}

	/** The number of turns the collectables.agent.Agent can be used after its creation*/
	private static final int baseWarranty = 5;
	private static final int effectDuration = 1;

	@Override
	public int getDuration() {
		return duration;
	}

	@Override
	public void setDuration(int duration) {
		Paralysis.duration = duration;
	}

	@Override
	public int getWarranty() {
		return warranty;
	}

	@Override
	public void setWarranty(int warranty) {
		Paralysis.warranty = warranty;
	}

	/** Applies the effects on a field.virologist.Virologist*/
	public void Apply(Virologist v) {
		if(v.GetMoveBehavior().GetPriority() < 2)
			v.SetMoveBehavior(new NotMove());
		v.SetCreateBehavior(new NotCreate());
		v.SetLearnBehavior(new NotLearn());
		v.SetStealBehavior(new NotSteal());
		v.SetPickUpBehavior(new NotPickUp());
		v.SetInfectBehavior(new NotInfect());
		v.SetDropBehavior(new NotDrop());
		v.SetGetStolenBehavior(new GetStolen());
	}

	@Override
	public String GetName(){ return "paralysis";}
}
