package assets.virologist.behavior.getstolenbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.getstolenbehavior.GetStolen.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.Collectable;
import assets.virologist.Virologist;

import java.util.ArrayList;
public class GetStolen implements GetStolenBehavior, java.io.Serializable {
    /**
     * The field.virologist.Virologist drops the desired item to the field.field.Field.
     *
     * @param v the target of the action
     * @param c the collectables.Collectable that the other field.virologist.Virologist wants to steal from the target
     * @return true, because the action was successful
     */
    @Override
    public boolean GetStolenFrom(Virologist v, ArrayList<Collectable> c) {
        v.DropCollectable(c);
        return true;
    }

    @Override
    public boolean CanStealForm(){
        return true;
    }
}
