package assets.virologist.behavior.getstolenbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.getstolenbehavior.GetStolenBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.Collectable;
import assets.virologist.Virologist;

import java.util.ArrayList;

/** The field.virologist.behavior which decides if another field.virologist.Virologist can steal from this field.virologist.Virologist */
public interface GetStolenBehavior {
	/**
	 *
	 * @param v the target of the action
	 * @param c the collectables.Collectable that the other field.virologist.Virologist wants to steal from the target
	 * @return true if the action was successful, false if the action fails
	 */
	boolean GetStolenFrom(Virologist v, ArrayList<Collectable> c);
	boolean CanStealForm();
}
