package assets.virologist.behavior.getstolenbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.getstolenbehavior.NotGetStolen.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.Collectable;
import assets.virologist.Virologist;

import java.util.ArrayList;
/** */
public class NotGetStolen implements GetStolenBehavior, java.io.Serializable {
    /**
     * Nothing happens.
     *
     * @param v the target of the action
     * @param c the collectables.Collectable that the other field.virologist.Virologist wants to steal from the target
     * @return false. because the action failed
     */
    @Override
    public boolean GetStolenFrom(Virologist v, ArrayList<Collectable> c) {
        return false;
    }

    @Override
    public boolean CanStealForm() {
        return false;
    }
}
