package assets.field;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.field.Shelter.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.Backpack;
import collectables.genome.Genome;
import java.util.ArrayList;

/** At the start of the game the Equipments are placed in Shelters*/
public class Shelter extends Field{
	/** Constructor*/
	public Shelter(){
		this.virologists = new ArrayList<>();
		this.neighbours = new ArrayList<>();
		backpack = new Backpack();
		neighbours.add(this);
	}

	@Override
	public Genome GetGenome() {
		return null;
	}
	@Override
	public String GetType(){
		return "shelter";
	}
}
