package assets.field;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.field.WareHouse.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.Backpack;

import java.util.ArrayList;

import collectables.genome.Genome;
/** At the start of the game collectables.material.Materials are placed in the WarHouses*/
public class WareHouse extends Field{
	/** Constructor*/
	public WareHouse(){
		this.virologists = new ArrayList<>();
		this.neighbours = new ArrayList<>();
		backpack = new Backpack();
		neighbours.add(this);
	}

	@Override
	public Genome GetGenome() {
		return null;
	}

	@Override
	public void DestroyMaterials(){
		backpack.getAminos().clear();
		backpack.getNucleotide().clear();
	}

	@Override
	public String GetType(){
		return "warehouse";
	}
}
