package collectables.material;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : collectables.material.Nucleotide.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//
import assets.Backpack;
import assets.virologist.Virologist;

public class Nucleotide extends Materials {
    /**
     * Adds a collectables.material.Nucleotide to a field.Backpack
     *
     * @param v the field.virologist.Virologist the backpack belongs to(Only used sometimes)
     * @param b the field.Backpack it gets added to
     * @return true if added successfully, false if the Nucleotide cannot be added
     */
    @Override
    public boolean AddToBackpack(Virologist v, Backpack b) {
        return b.add(this);
    }

    /**
     * Removes a collectables.material.Nucleotide from a field.Backpack
     *
     * @param v the field.virologist.Virologist the backpack belongs to(Only used sometimes)
     * @param b the field.Backpack it gets removed from
     */
    @Override
    public void RemoveFromBackpack(Virologist v, Backpack b) {
        b.Remove(this);
    }

    @Override
    public String getName(){ return "Nucleotide";}
}
