package assets.virologist.behavior.learnbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.learnbehavior.NotLearn.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.virologist.Virologist;
public class NotLearn implements LearnBehavior, java.io.Serializable {
    /**
     * Nothing happens
     *
     * @param v the field.virologist.Virologist who wants to learn the collectables.genome.Genome
     */
    @Override
    public void LearnGenome(Virologist v) {
    }
}
