package assets.virologist.behavior.stealbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.stealbehavior.StealBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.Collectable;
import assets.virologist.Virologist;

import java.util.ArrayList;

/** The field.virologist.behavior which decides if the field.virologist.Virologist can steal from another field.virologist.Virologist */
public interface StealBehavior {
	/**
	 *
	 * @param v1 the field.virologist.Virologist who wants to steal
	 * @param v2 the target of the action
	 * @param c the Collectables v1 wants to steal
	 */
	void StealFromVirologist(Virologist v1, Virologist v2, ArrayList<Collectable> c);
}
