package assets.virologist.behavior.getinfectedbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.getinfectedbehavior.InfectBack.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.agent.Agent;
import assets.virologist.Virologist;
import collectables.equipment.Gloves;
public class InfectBack implements GetInfectedBehavior, java.io.Serializable{
    final private Gloves glove;
    public InfectBack(Gloves glove){
        this.glove=glove;
    }
    @Override
    public int GetPriority() {
        return 3;
    }

    /**
     * v1 will get infected regardless of his protection level.
     *
     * @param v1 the field.virologist.Virologist who wants to infect
     * @param v2 the target of the action
     * @param a the Agents v1 wants to infect v2 with
     */

    @Override
    public void getInfected(Virologist v1, Virologist v2, Agent a) {
        v1.GetInfected(v2, a);
        glove.DecreaseEquipmentDurability();
        if(glove.GetDurability() == 0)
            glove.RemoveFromBackpack(v2, v2.getBackpack());
    }

    @Override
    public void getInfectedRandomOff(Virologist v1, Virologist v2, Agent a) {
        getInfected(v1,v2,a);
    }
}
