package assets.virologist.behavior.getinfectedbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.getinfectedbehavior.MaybeInfected.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.agent.Agent;
import assets.virologist.Virologist;
public class MaybeInfected implements GetInfectedBehavior, java.io.Serializable {
    @Override
    public int GetPriority() {
        return 1;
    }

    /**
     * There is a chance v2 gets infected with the collectables.agent.Agent
     *
     * @param v1 the field.virologist.Virologist who wants to infect
     * @param v2 the target of the action
     * @param a the Agents v1 wants to infect v2 with
     */

    @Override
    public void getInfected(Virologist v1, Virologist v2, Agent a) {
        double d = Math.random();
        if(d < 0.823){
            a.Apply(v2);
            v2.GetBackpack().AddApplied(a);
        }
    }

    @Override
    public void getInfectedRandomOff(Virologist v1, Virologist v2, Agent a) {
        //not get infected
    }
}
