package assets.virologist.behavior.pickupbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.pickupbehavior.PickUpBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.Collectable;
import assets.virologist.Virologist;

import java.util.ArrayList;

/** The field.virologist.behavior which decides if the field.virologist.Virologist can pick up a collectables.Collectable */
public interface PickUpBehavior {
	/**
	 *
	 * @param v the field.virologist.Virologist who wants to pick up something
	 * @param c the Collectables the field.virologist.Virologist wants to pick up
	 */
	void PickUpCollectable(Virologist v, ArrayList<Collectable> c);
}
