package collectables.equipment;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : collectables.equipment.Cloak.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import assets.virologist.Virologist;
import assets.virologist.behavior.getinfectedbehavior.MaybeInfected;
import collectables.equipment.Equipment;

/** The collectables.equipment.Cloak protects the field.virologist.Virologist from Agents with an 82.3% chance*/
public class Cloak extends Equipment {
	public Cloak(){
		durability=-1;
	}

	@Override
	public void DecreaseEquipmentDurability() {

	}

	/** Applies the effect to the field.virologist.Virologist if there is no stronger effect on him*/
	public void Apply(Virologist v) {
		if(v.GetGetInfectedBehavior().GetPriority() < 1)
			v.SetGetInfectedBehavior(new MaybeInfected());
	}

	@Override
	public String GetName() {
		return "cloak";
	}

	@Override
	public int GetDurability(){
		return -1;
	}
}
