package assets.virologist.behavior.dropbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.dropbehavior.DropBehavior.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.Collectable;
import assets.virologist.Virologist;

import java.util.ArrayList;

/** The field.virologist.behavior which decides if the field.virologist.Virologist can drop a few Collectables */
public interface DropBehavior {
	/**
	 *
	 * @param v The field.virologist.Virologist who wants to drop
	 * @param c The Collectables he wants to drop
	 */
	void DropCollectable(Virologist v, ArrayList<Collectable> c);
}
