package assets.virologist.behavior.dropbehavior;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : field.virologist.behavior.dropbehavior.NotDrop.java
//  @ Date : 2022. 03. 23.
//  @ Author : 
//
//

import collectables.Collectable;
import assets.virologist.Virologist;
import java.util.ArrayList;

public class NotDrop implements DropBehavior, java.io.Serializable {
    /**
     * Nothing happens.
     *
     * @param v The field.virologist.Virologist who wants to drop
     * @param c The Collectables he wants to drop
     */
    @Override
    public void DropCollectable(Virologist v, ArrayList<Collectable> c) {
    }
}
